export default {
  phrase: 'drinking too much at a party',
  maxResults: 10,
  locationRadius: '20mi',
  delay: 4000,
  voice: 'Salli',
  poem: [
    {'line': 0, 'text': 'Question: why am I here?', 'interval': 2000},
    {'line': 1, 'text': 'Second question,', 'interval': 1700},
    {'line': 2, 'text': 'why am I afraid of a truck', 'interval': 1900},
    {'line': 3, 'text': 'crushing my car against a tree', 'interval': 2200},
    {'line': 4, 'text': 'Why are all my nightmares truck-based?', 'interval': 2300},
    {'line': 5, 'text': 'Why are people so afraid', 'interval': 2000},
    {'line': 6, 'text': 'of large things crushing them', 'interval': 1800},
    {'line': 7, 'text': 'Our bones can withstand', 'interval': 1400},
    {'line': 8, 'text': 'the torment of years,', 'interval': 1500},
    {'line': 9, 'text': 'even as the world disintegrates,', 'interval': 1800},
    {'line': 10, 'text': 'becomes sound,', 'interval': 1200},
    {'line': 11, 'text': 'becomes pieces of color and sugar', 'interval': 2100},
    {'line': 12, 'text': 'on someone’s tongue.', 'interval': 1500},
    {'line': 13, 'text': 'My hand can create a mark', 'interval': 2000},
    {'line': 14, 'text': 'on your face, in a bar', 'interval': 2000},
    {'line': 15, 'text': 'in hong kong.', 'interval': 1500},
    {'line': 16, 'text': 'You will order pickled squid', 'interval': 2000},
    {'line': 17, 'text': 'and touch your cheek', 'interval': 1700},
    {'line': 18, 'text': 'as if I had not meant to hurt you.', 'interval': 2000},
    {'line': 19, 'text': 'We will meet the others', 'interval': 1800},
    {'line': 20, 'text': 'for karaoke and salty peanuts', 'interval': 2000},
    {'line': 21, 'text': 'that will leave us hoarse,', 'interval': 1700},
    {'line': 22, 'text': 'begging for more beer,', 'interval': 1700},
    {'line': 23, 'text': 'for another song,', 'interval': 1500},
    {'line': 24, 'text': 'just until it’s 6 am', 'interval': 2000},
    {'line': 25, 'text': 'and the light of the day', 'interval': 1800},
    {'line': 26, 'text': 'will make it okay', 'interval': 1500},
    {'line': 27, 'text': 'to put on our suits', 'interval': 1700},
    {'line': 28, 'text': 'and to meet the others', 'interval': 1700},
    {'line': 29, 'text': 'in their suits', 'interval': 1500},
    {'line': 30, 'text': 'and we will form a line of suits', 'interval': 2000},
    {'line': 31, 'text': 'until no one knows', 'interval': 1800},
    {'line': 32, 'text': 'which one of us', 'interval': 1800},
    {'line': 33, 'text': 'fell to the gutter,', 'interval': 1800},
    {'line': 34, 'text': 'crying and puking and praying.', 'interval': 2200},
    {'line': 35, 'text': '“where are you?!”', 'interval': 1500},
    {'line': 36, 'text': 'shouted one of us,', 'interval': 1800},
    {'line': 37, 'text': 'into the night', 'interval': 1500},
    {'line': 38, 'text': 'that will never know the true culprit.', 'interval': 2000, 'last': true}
  ]
}