/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:a1b29beb-8f9c-4ae0-808d-6488ce43e5f1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_z525lQPkk",
    "aws_user_pools_web_client_id": "7dphkaonmrmoheh3en43bil7s7",
    "oauth": {},
    "aws_user_files_s3_bucket": "gallery-content11249-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
